In [7]:
import numpy as np
from scipy.signal import convolve2d

# Define the 2D matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define the 2D kernel
K = np.array([[0, 1, 0],
              [1, -4, 1],
              [0, 1, 0]])

# Pad the array to simulate periodic boundaries
pad_width = (len(K) - 1) // 2
A_padded = np.pad(A, pad_width, mode='wrap')

# Perform the convolution
result = convolve2d(A_padded, K, mode='valid')

# Crop to the original size
result = result[:A.shape[0], :A.shape[1]]
print(result)


[[ 12   9   6]
 [  3   0  -3]
 [ -6  -9 -12]]


In [10]:
print(pad_width)
A_padded = np.pad(A, pad_width+1, mode='wrap')
print(A_padded)
print(convolve2d(A_padded, K, mode='valid'))

1
[[5 6 4 5 6 4 5]
 [8 9 7 8 9 7 8]
 [2 3 1 2 3 1 2]
 [5 6 4 5 6 4 5]
 [8 9 7 8 9 7 8]
 [2 3 1 2 3 1 2]
 [5 6 4 5 6 4 5]]
[[-12  -6  -9 -12  -6]
 [  6  12   9   6  12]
 [ -3   3   0  -3   3]
 [-12  -6  -9 -12  -6]
 [  6  12   9   6  12]]
